2025-03-17 17:43:56.514 | INFO     | app:create_app:66 - Application started with environment: development
2025-03-17 17:44:04.094 | DEBUG    | app.routes.credentials:edit:204 - Editing credential ID 1 of type sftp
2025-03-17 17:44:35.244 | DEBUG    | app.routes.credentials:edit:204 - Editing credential ID 1 of type sftp
2025-03-17 17:44:39.461 | INFO     | app.routes.credentials:test:386 - Testing credential ID 1 (TestUser1) of type sftp
2025-03-17 17:44:39.461 | DEBUG    | app.routes.credentials:test:394 - SFTP connection test initiated: transfer.slicedhealth.com:22 with user testuser1
2025-03-17 17:44:39.461 | DEBUG    | app.utils.sftp_utils:connect:37 - Attempting to connect to SFTP server: transfer.slicedhealth.com:22 with username: testuser1 from local IP: 172.16.2.33
2025-03-17 17:44:39.462 | WARNING  | app.utils.sftp_utils:connect:41 - Host key checking disabled for transfer.slicedhealth.com
2025-03-17 17:44:39.462 | DEBUG    | app.utils.sftp_utils:connect:65 - Using password authentication
2025-03-17 17:44:39.482 | ERROR    | app.utils.sftp_utils:connect:83 - Connection reset by server transfer.slicedhealth.com. This could indicate a firewall blocking the connection from 172.16.2.33, incorrect port, or server rejecting the connection.
2025-03-17 17:44:39.482 | DEBUG    | app.utils.sftp_utils:connect:93 - SSH Exception details: Traceback (most recent call last):
  File "/home/ec2-user/transferwizard/.venv/lib64/python3.9/site-packages/paramiko/transport.py", line 2292, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/ec2-user/transferwizard/.venv/lib64/python3.9/site-packages/paramiko/packet.py", line 374, in readline
    buf += self._read_timeout(timeout)
  File "/home/ec2-user/transferwizard/.venv/lib64/python3.9/site-packages/paramiko/packet.py", line 601, in _read_timeout
    x = self.__socket.recv(128)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/transferwizard/app/utils/sftp_utils.py", line 71, in connect
    self.connection = pysftp.Connection(**connect_kwargs)
  File "/home/ec2-user/transferwizard/.venv/lib64/python3.9/site-packages/pysftp/__init__.py", line 143, in __init__
    self._transport.connect(**self._tconnect)
  File "/home/ec2-user/transferwizard/.venv/lib64/python3.9/site-packages/paramiko/transport.py", line 1369, in connect
    self.start_client()
  File "/home/ec2-user/transferwizard/.venv/lib64/python3.9/site-packages/paramiko/transport.py", line 722, in start_client
    raise e
  File "/home/ec2-user/transferwizard/.venv/lib64/python3.9/site-packages/paramiko/transport.py", line 2113, in run
    self._check_banner()
  File "/home/ec2-user/transferwizard/.venv/lib64/python3.9/site-packages/paramiko/transport.py", line 2296, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer

2025-03-17 17:44:39.483 | ERROR    | app.utils.sftp_utils:test_connection:149 - SFTP connection test failed (SSH error): Error reading SSH protocol banner[Errno 104] Connection reset by peer
2025-03-17 17:44:39.483 | INFO     | app.routes.credentials:test:441 - Credential test result: False
2025-03-17 18:02:40.599 | INFO     | app.routes.credentials:test:386 - Testing credential ID 1 (TestUser1) of type sftp
2025-03-17 18:02:40.600 | DEBUG    | app.routes.credentials:test:394 - SFTP connection test initiated: transfer.slicedhealth.com:22 with user testuser1
2025-03-17 18:02:40.600 | DEBUG    | app.utils.sftp_utils:connect:37 - Attempting to connect to SFTP server: transfer.slicedhealth.com:22 with username: testuser1 from local IP: 172.16.2.33
2025-03-17 18:02:40.600 | WARNING  | app.utils.sftp_utils:connect:41 - Host key checking disabled for transfer.slicedhealth.com
2025-03-17 18:02:40.600 | DEBUG    | app.utils.sftp_utils:connect:65 - Using password authentication
2025-03-17 18:02:40.728 | INFO     | app.utils.sftp_utils:connect:72 - Successfully connected to SFTP server: transfer.slicedhealth.com from local IP: 172.16.2.33
2025-03-17 18:02:40.728 | DEBUG    | app.utils.sftp_utils:test_connection:139 - Testing connection by listing current directory on transfer.slicedhealth.com from 172.16.2.33
2025-03-17 18:02:41.733 | DEBUG    | app.utils.sftp_utils:test_connection:143 - Directory listing successful: 6549 items found
2025-03-17 18:02:41.733 | DEBUG    | app.utils.sftp_utils:disconnect:131 - Disconnecting from SFTP server: transfer.slicedhealth.com
2025-03-17 18:02:41.734 | INFO     | app.routes.credentials:test:441 - Credential test result: True
2025-03-17 18:08:33.246 | INFO     | app.routes.credentials:test:386 - Testing credential ID 2 (testuser4) of type sftp
2025-03-17 18:08:33.246 | DEBUG    | app.routes.credentials:test:394 - SFTP connection test initiated: transfer.slicedhealth.com:22 with user testuser4
2025-03-17 18:08:33.247 | DEBUG    | app.utils.sftp_utils:connect:37 - Attempting to connect to SFTP server: transfer.slicedhealth.com:22 with username: testuser4 from local IP: 172.16.2.33
2025-03-17 18:08:33.247 | WARNING  | app.utils.sftp_utils:connect:41 - Host key checking disabled for transfer.slicedhealth.com
2025-03-17 18:08:33.247 | DEBUG    | app.utils.sftp_utils:connect:65 - Using password authentication
2025-03-17 18:08:33.451 | INFO     | app.utils.sftp_utils:connect:72 - Successfully connected to SFTP server: transfer.slicedhealth.com from local IP: 172.16.2.33
2025-03-17 18:08:33.451 | DEBUG    | app.utils.sftp_utils:test_connection:139 - Testing connection by listing current directory on transfer.slicedhealth.com from 172.16.2.33
2025-03-17 18:08:33.524 | DEBUG    | app.utils.sftp_utils:test_connection:143 - Directory listing successful: 14 items found
2025-03-17 18:08:33.524 | DEBUG    | app.utils.sftp_utils:disconnect:131 - Disconnecting from SFTP server: transfer.slicedhealth.com
2025-03-17 18:08:33.525 | INFO     | app.routes.credentials:test:441 - Credential test result: True
